export const SULIFU_IN_BANK_CODES: Record<string, string> = {
  yesb: 'Yes Bank',
  dp_abpb_in: 'Aditya Birla Payments Bank',
  dp_apb_in: 'Airtel Payments Bank',
  dp_allahabad_in: 'Allahabad Bank',
  dp_andhra_in: 'Andhra Bank',
  dp_apgvb_in: 'Andhra Pradesh Grameena Vikas Bank',
  dp_apgb_in: 'Andhra Pragathi Grameena Bank',
  dp_aprb_in: 'Arunachal Pradesh Rural Bank',
  dp_aryavart_in: 'Aryavart Bank',
  dp_agvb_in: 'Assam Gramin Vikash Bank',
  dp_asfb_in: 'AU Small Finance Bank',
  dp_axisbank_in: 'Axis Bank',
  dp_bandhanbank_in: 'Bandhan Bank',
  dp_bgvb_in: 'Bangiya Gramin Vikash Bank',
  dp_bbk_in: 'Bank of Bahrain and Kuwait',
  dp_bob_in: 'Bank of Baroda',
  dp_bankofindia_in: 'Bank of India',
  dp_bom_in: 'Bank of Maharashtra',
  dp_bggb_in: 'Baroda Gujarat Gramin Bank',
  dp_brkgb_in: 'Baroda Rajasthan Kshetriya Gramin Bank',
  dp_bupg_in: 'Baroda Uttar Pradesh Gramin Bank',
  dp_bccb_in: 'Bassein Catholic Co-operative Bank',
  dp_bharat_in: 'Bharat Bank',
  dp_canarabank_in: 'Canara Bank',
  dp_csf_in: 'Capital Small Finance Bank',
  dp_cboi_in: 'Central Bank of India',
  dp_cggb_in: 'Chaitanya Godavari Grameena Bank',
  dp_crgb_in: 'Chhattisgarh Rajya Gramin Bank',
  dp_citi_in: 'Citi India',
  dp_cub_in: 'City Union Bank',
  dp_coastal_in: 'COASTAL BANK',
  dp_corp_in: 'Corporation Bank',
  dp_cosmos_in: 'Cosmos Co-operative Bank Ltd',
  dp_csb_in: 'CSB Bank',
  dp_dbg_in: 'Dakshin Bihar Gramin Bank',
  dp_dcb_in: 'DCB Bank',
  dp_dena_in: 'Dena Bank',
  dp_db_in: 'Deutsche Bank',
  dp_dhan_in: 'Dhanlaxmi Bank',
  dp_edb_in: 'Ellaquai Dehati Bank',
  dp_equitas_in: 'Equitas Bank',
  dp_esaf_in: 'ESAF Small Finance Bank',
  dp_exim_in: 'Exim Bank',
  dp_federal_in: 'Federal Bank',
  dp_fincare_in: 'Fincare Small Finance Bank',
  dp_fino_in: 'Fino Payments Bank',
  dp_gpp_in: 'GP Parsik Sahakari Bank',
  dp_hdfcbank_in: 'HDFC Bank',
  dp_hpgb_in: 'Himachal Pradesh Gramin Bank',
  dp_hsbc_in: 'HSBC India',
  dp_icicbank_in: 'ICICI Bank',
  dp_idbibank_in: 'IDBI Bank',
  dp_idfc_in: 'IDFC First Bank Limited',
  dp_ippb_in: 'India Post Payments Bank',
  dp_indian_in: 'Indian Bank',
  dp_iob_in: 'Indian Overseas Bank',
  dp_indusind_in: 'IndusInd Bank',
  dp_jkgb_in: 'J&K Grameen Bank',
  dp_jkb_in: 'Jammu & Kashmir Bank',
  dp_jana_in: 'Jana Small Finance Bank',
  dp_jsb_in: 'JANATA SAHAKARI BANK PUNE',
  dp_jrgb_in: 'Jharkhand Rajya Gramin Bank',
  dp_jpb_in: 'Jio Payments Bank',
  dp_ktk_in: 'Karnataka Bank',
  dp_karnatakag_in: 'Karnataka Gramin Bank',
  dp_kvgb_in: 'Karnataka Vikas Grameena Bank',
  dp_kvb_in: 'Karur Vysya Bank',
  dp_kgsg_in: 'Kashi Gomti Samyut Gramin Bank',
  dp_keralag_in: 'Kerala Gramin Bank',
  dp_kotak_in: 'Kotak Mahindra Bank',
  dp_mbgb_in: 'Madhya Bihar Gramin Bank',
  dp_madhyanchalg_in: 'Madhyanchal Gramin Bank',
  dp_maharashtrag_in: 'Maharashtra Gramin Bank',
  dp_manipurr_in: 'Manipur Rural Bank',
  dp_meghalayar_in: 'Meghalaya Rural Bank',
  dp_mizoramr_in: 'Mizoram Rural Bank',
  dp_nainital_in: 'Nainital Bank',
  dp_nesfb_in: 'North East Small Finance Bank',
  dp_paytm_in: 'Paytm Payments Bank',
  dp_dbs_in: 'PT Bank DBS Indonesia',
  dp_psb_in: 'Punjab & Sind Bank',
  dp_pnb_in: 'Punjab National Bank',
  dp_rbl_in: 'RBL Bank',
  dp_rboi_in: 'Reserve Bank of India',
  dp_idbi_in: 'Small Industries Development Bank of India',
  dp_sib_in: 'South Indian Bank',
  dp_sc_in: 'Standard Chartered Thailand',
  dp_sboi_in: 'State Bank of India',
  dp_suryoday_in: 'SuryodayBank',
  dp_tmb_in: 'Tamilnad Mercantile Bank Limited',
  dp_uco_in: 'UCO Bank',
  dp_ujjivansfb_in: 'Ujjivan Small Finance Bank',
  dp_union_in: 'Union Bank of India',
  dp_uboi_in: 'United Bank of India',
  dp_usfb_in: 'Utkarsh Small Finance Bank',
  dp_yes_in: 'Yes Bank',
};

export const SULIFU_IN_BANK_CODE_SET = new Set(
  Object.keys(SULIFU_IN_BANK_CODES).flatMap((code) => [code, code.toUpperCase()])
);
